# Generated by Django 5.0.2 on 2025-05-21 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routines", "0004_uploadprogress_alter_mediaasset_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="breathingexercise",
            name="audio_cues",
            field=models.JSONField(
                default=dict, help_text="Audio cue configuration for breath timing"
            ),
        ),
        migrations.AddField(
            model_name="breathingexercise",
            name="background_sounds",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"asset_type": "audio"},
                related_name="breathing_background_sounds",
                to="routines.mediaasset",
            ),
        ),
        migrations.AddField(
            model_name="breathingexercise",
            name="benefits",
            field=models.JSONField(
                default=list,
                help_text="List of benefits (e.g., ['Calming', 'Energy Boost'])",
            ),
        ),
        migrations.AddField(
            model_name="breathingexercise",
            name="consistency_goals",
            field=models.JSONField(
                default=dict, help_text="Goals for consistent practice"
            ),
        ),
        migrations.AddField(
            model_name="breathingexercise",
            name="difficulty_level",
            field=models.CharField(
                choices=[
                    ("beginner", "Beginner"),
                    ("intermediate", "Intermediate"),
                    ("advanced", "Advanced"),
                ],
                default="beginner",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="breathingexercise",
            name="focus_areas",
            field=models.JSONField(
                default=list,
                help_text="List of focus areas (e.g., ['Stress Relief', 'Focus'])",
            ),
        ),
        migrations.AddField(
            model_name="breathingexercise",
            name="mastery_criteria",
            field=models.JSONField(
                default=dict, help_text="Criteria for mastering the exercise"
            ),
        ),
        migrations.AddField(
            model_name="breathingexercise",
            name="progression_milestones",
            field=models.JSONField(
                default=list, help_text="List of progression milestones"
            ),
        ),
        migrations.AddField(
            model_name="breathingexercise",
            name="visual_cues",
            field=models.JSONField(
                default=dict, help_text="Visual cue configuration for breath timing"
            ),
        ),
        migrations.AddField(
            model_name="meditationsession",
            name="achievement_criteria",
            field=models.JSONField(
                default=dict, help_text="Criteria for session achievement"
            ),
        ),
        migrations.AddField(
            model_name="meditationsession",
            name="background_sounds",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"asset_type": "audio"},
                related_name="meditation_background_sounds",
                to="routines.mediaasset",
            ),
        ),
        migrations.AddField(
            model_name="meditationsession",
            name="background_visuals",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"asset_type__in": ["image", "video"]},
                related_name="meditation_background_visuals",
                to="routines.mediaasset",
            ),
        ),
        migrations.AddField(
            model_name="meditationsession",
            name="difficulty_level",
            field=models.CharField(
                choices=[
                    ("beginner", "Beginner"),
                    ("intermediate", "Intermediate"),
                    ("advanced", "Advanced"),
                ],
                default="beginner",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="meditationsession",
            name="focus_level_assessment",
            field=models.JSONField(
                default=dict, help_text="Assessment criteria for focus levels"
            ),
        ),
        migrations.AddField(
            model_name="meditationsession",
            name="focus_points",
            field=models.JSONField(
                default=list, help_text="List of focus points for the meditation"
            ),
        ),
        migrations.AddField(
            model_name="meditationsession",
            name="guided_sequence",
            field=models.JSONField(
                default=list, help_text="Sequence of guided meditation steps"
            ),
        ),
        migrations.AddField(
            model_name="meditationsession",
            name="meditation_type",
            field=models.CharField(
                choices=[
                    ("mindfulness", "Mindfulness"),
                    ("loving_kindness", "Loving-Kindness"),
                    ("body_scan", "Body Scan"),
                    ("breath_focus", "Breath Focus"),
                    ("transcendental", "Transcendental"),
                    ("zen", "Zen"),
                    ("vipassana", "Vipassana"),
                ],
                default="mindfulness",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="meditationsession",
            name="mindfulness_prompts",
            field=models.JSONField(
                default=list, help_text="List of mindfulness prompts"
            ),
        ),
        migrations.AddField(
            model_name="meditationsession",
            name="progression_path",
            field=models.JSONField(
                default=list, help_text="Progression path for the meditation type"
            ),
        ),
        migrations.AddField(
            model_name="meditationsession",
            name="session_goals",
            field=models.JSONField(
                default=dict, help_text="Goals for the meditation session"
            ),
        ),
        migrations.AddField(
            model_name="meditationsession",
            name="transition_points",
            field=models.JSONField(
                default=list, help_text="Points of transition in the meditation"
            ),
        ),
    ]
