# Generated by Django 5.0.2 on 2025-05-21 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routines", "0005_breathingexercise_audio_cues_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="breathingexercise",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="meditationsession",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveIndex(
            model_name="mediaasset",
            name="routines_me_asset_t_198172_idx",
        ),
        migrations.RemoveIndex(
            model_name="mediaasset",
            name="routines_me_instruc_308978_idx",
        ),
        migrations.RemoveIndex(
            model_name="uploadprogress",
            name="routines_up_upload__8dff74_idx",
        ),
        migrations.RemoveIndex(
            model_name="uploadprogress",
            name="routines_up_status_d3d01a_idx",
        ),
        migrations.RemoveIndex(
            model_name="uploadprogress",
            name="routines_up_instruc_e59392_idx",
        ),
        migrations.RemoveField(
            model_name="breathingexercise",
            name="audio_cues",
        ),
        migrations.RemoveField(
            model_name="breathingexercise",
            name="background_sounds",
        ),
        migrations.RemoveField(
            model_name="breathingexercise",
            name="benefits",
        ),
        migrations.RemoveField(
            model_name="breathingexercise",
            name="consistency_goals",
        ),
        migrations.RemoveField(
            model_name="breathingexercise",
            name="focus_areas",
        ),
        migrations.RemoveField(
            model_name="breathingexercise",
            name="pattern",
        ),
        migrations.RemoveField(
            model_name="breathingexercise",
            name="progression_milestones",
        ),
        migrations.RemoveField(
            model_name="breathingexercise",
            name="timer_seconds",
        ),
        migrations.RemoveField(
            model_name="breathingexercise",
            name="visual_cues",
        ),
        migrations.RemoveField(
            model_name="mediaasset",
            name="file_path",
        ),
        migrations.RemoveField(
            model_name="mediaasset",
            name="instructor",
        ),
        migrations.RemoveField(
            model_name="mediaasset",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="mediaasset",
            name="url",
        ),
        migrations.RemoveField(
            model_name="meditationsession",
            name="audio_assets",
        ),
        migrations.RemoveField(
            model_name="meditationsession",
            name="background_sounds",
        ),
        migrations.RemoveField(
            model_name="meditationsession",
            name="background_visuals",
        ),
        migrations.RemoveField(
            model_name="meditationsession",
            name="duration_seconds",
        ),
        migrations.RemoveField(
            model_name="meditationsession",
            name="guided_sequence",
        ),
        migrations.RemoveField(
            model_name="meditationsession",
            name="media_assets",
        ),
        migrations.RemoveField(
            model_name="meditationsession",
            name="meditation_type",
        ),
        migrations.RemoveField(
            model_name="meditationsession",
            name="mindfulness_prompts",
        ),
        migrations.RemoveField(
            model_name="meditationsession",
            name="progression_path",
        ),
        migrations.RemoveField(
            model_name="meditationsession",
            name="script",
        ),
        migrations.RemoveField(
            model_name="meditationsession",
            name="session_goals",
        ),
        migrations.RemoveField(
            model_name="meditationsession",
            name="transition_points",
        ),
        migrations.RemoveField(
            model_name="uploadprogress",
            name="completed_at",
        ),
        migrations.RemoveField(
            model_name="uploadprogress",
            name="file_path",
        ),
        migrations.RemoveField(
            model_name="uploadprogress",
            name="instructor",
        ),
        migrations.RemoveField(
            model_name="uploadprogress",
            name="metadata",
        ),
        migrations.RemoveField(
            model_name="uploadprogress",
            name="total_size",
        ),
        migrations.RemoveField(
            model_name="uploadprogress",
            name="upload_id",
        ),
        migrations.RemoveField(
            model_name="uploadprogress",
            name="uploaded_size",
        ),
        migrations.AddField(
            model_name="breathingexercise",
            name="cue_style",
            field=models.CharField(
                choices=[
                    ("minimal", "Minimal"),
                    ("guided", "Guided"),
                    ("nature", "Nature Sounds"),
                ],
                default="minimal",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="breathingexercise",
            name="cycles",
            field=models.PositiveIntegerField(
                default=1, help_text="Number of breath cycles"
            ),
        ),
        migrations.AddField(
            model_name="breathingexercise",
            name="exhale_duration",
            field=models.PositiveIntegerField(
                default=4, help_text="Duration of exhale in seconds"
            ),
        ),
        migrations.AddField(
            model_name="breathingexercise",
            name="has_audio_cue",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="breathingexercise",
            name="has_visual_cue",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="breathingexercise",
            name="hold_duration",
            field=models.PositiveIntegerField(
                default=0, help_text="Duration of breath hold in seconds"
            ),
        ),
        migrations.AddField(
            model_name="breathingexercise",
            name="inhale_duration",
            field=models.PositiveIntegerField(
                default=4, help_text="Duration of inhale in seconds"
            ),
        ),
        migrations.AddField(
            model_name="breathingexercise",
            name="pattern_type",
            field=models.CharField(
                choices=[
                    ("equal", "Equal Breathing"),
                    ("box", "Box Breathing"),
                    ("478", "4-7-8 Breathing"),
                    ("custom", "Custom Pattern"),
                ],
                default="equal",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="media_assets/"),
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="supabase_bucket",
            field=models.CharField(
                blank=True, help_text="Supabase bucket name", max_length=64, null=True
            ),
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="supabase_path",
            field=models.CharField(
                blank=True,
                help_text="Path in Supabase storage",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="meditationsession",
            name="ambient_sound_type",
            field=models.CharField(
                choices=[
                    ("nature", "Nature Sounds"),
                    ("music", "Meditation Music"),
                    ("silence", "Silence"),
                    ("custom", "Custom"),
                ],
                default="nature",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="meditationsession",
            name="background_audio",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"asset_type": "audio"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="meditation_background",
                to="routines.mediaasset",
            ),
        ),
        migrations.AddField(
            model_name="meditationsession",
            name="duration_minutes",
            field=models.PositiveIntegerField(
                default=10, help_text="Default session duration in minutes"
            ),
        ),
        migrations.AddField(
            model_name="meditationsession",
            name="guided_audio",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"asset_type": "audio"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="meditation_guided",
                to="routines.mediaasset",
            ),
        ),
        migrations.AddField(
            model_name="meditationsession",
            name="guided_script",
            field=models.TextField(
                blank=True, default="", help_text="Guided meditation script"
            ),
        ),
        migrations.AddField(
            model_name="meditationsession",
            name="has_ambient_sounds",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="meditationsession",
            name="has_visual_guide",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="meditationsession",
            name="session_type",
            field=models.CharField(
                choices=[
                    ("mindfulness", "Mindfulness"),
                    ("loving_kindness", "Loving-Kindness"),
                    ("body_scan", "Body Scan"),
                    ("breath_focus", "Breath Focus"),
                    ("custom", "Custom"),
                ],
                default="mindfulness",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="uploadprogress",
            name="progress",
            field=models.PositiveIntegerField(
                default=0, help_text="Upload progress percentage"
            ),
        ),
        migrations.AlterField(
            model_name="breathingexercise",
            name="mastery_criteria",
            field=models.JSONField(
                default=dict,
                help_text="Criteria for mastering this exercise (e.g., {'cycles_completed': 10, 'consistency_days': 7})",
            ),
        ),
        migrations.AlterField(
            model_name="mediaasset",
            name="asset_type",
            field=models.CharField(
                choices=[("image", "Image"), ("video", "Video"), ("audio", "Audio")],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="mediaasset",
            name="duration_seconds",
            field=models.PositiveIntegerField(
                blank=True, help_text="Duration for video/audio in seconds", null=True
            ),
        ),
        migrations.AlterField(
            model_name="mediaasset",
            name="name",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="mediaasset",
            name="thumbnail_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="URL for video thumbnail or image preview",
            ),
        ),
        migrations.AlterField(
            model_name="meditationsession",
            name="achievement_criteria",
            field=models.JSONField(
                default=dict,
                help_text="Criteria for achieving mastery of this meditation",
            ),
        ),
        migrations.AlterField(
            model_name="meditationsession",
            name="focus_level_assessment",
            field=models.JSONField(
                default=dict,
                help_text="Criteria for assessing focus level during session",
            ),
        ),
        migrations.AlterField(
            model_name="meditationsession",
            name="focus_points",
            field=models.JSONField(
                default=list, help_text="List of focus points or mindfulness prompts"
            ),
        ),
        migrations.AlterField(
            model_name="uploadprogress",
            name="asset_type",
            field=models.CharField(
                choices=[("image", "Image"), ("video", "Video"), ("audio", "Audio")],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="uploadprogress",
            name="error_message",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="uploadprogress",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("uploading", "Uploading"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
    ]
