# Generated by Django 5.0.2 on 2025-05-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Phone number in international format",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="preferences",
            field=models.JSONField(
                default=dict,
                help_text="User preferences (notifications, email updates, etc.)",
            ),
        ),
    ]
